### ISSUE TITLE
Browse Queue RabbitMQ  error

### ISSUE THREAD

**Issue by RomanRabirokh** [klyashko/jms-messenger#2]
IDE: **PHP STORM 2018 3.3**
Version Plugin: **v0.9.0**
  [{rabbit,"RabbitMQ",**"3.6.10**"},

Config default 
Server type **Rabbit_MQ**
Connection Type: **TCP**
Host: **localhost**
Port **5672**
Name **localhost:5672**

When i browse  queue RabbitMQ i have error
queue have size one element.
Connection successful. 

An exception han been thrown during loading messages from a queue
Details: queue-query

java.io.StreamCorruptedException: invalid stream header: 7B227061
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:857)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at com.rabbitmq.jms.util.WhiteListObjectInputStream.<init>(WhiteListObjectInputStream.java:63)
	at com.idea.tools.jms.RabbitMQConnectionStrategy.deserialize(RabbitMQConnectionStrategy.java:63)
	at com.idea.tools.jms.RabbitMQConnectionStrategy.map(RabbitMQConnectionStrategy.java:54)
	at com.idea.tools.service.JmsService.receive(JmsService.java:89)
	at com.idea.tools.task.LoadMessagesTask.run(LoadMessagesTask.java:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by klyashko** [comment]
Hi Roman.

I'll check it in the nearest time.

**Comment by RomanRabirokh** [comment]
> Hi Roman.
> 
> I'll check it in the nearest time.
> 
> @RomanRabirokh What client has sent that message?

Hi)
This is sent me IDE PHPSTORM 2018 3.3, in window IDE fatal errors, file stacktrace.txt. When i click "Browse queue".
is that what you mean?

In the Rabbitmq web interface, I have jms.durable.queues with the necessary ones bindings

**Comment by klyashko** [comment]
@RomanRabirokh not exactly.
I mean how that message got to a queue?
Did you send it vie web interface, the plugin or by your application?

**Comment by RomanRabirokh** [comment]
@klyashko 
I send message to a queue from my php aplication.

**Comment by klyashko** [comment]
@RomanRabirokh 
Ok, I'll check it.

**Comment by klyashko** [comment]
@RomanRabirokh Hi.
Version 1.0.1 is available in the repository.  Can you check that it fixes your problem?

**Comment by RomanRabirokh** [comment]
@klyashko 
Hi)
It works!) Thank you)

**Comment by klyashko** [comment]
Welcome)
