### ISSUE TITLE
Browse ActiveMQ messages with some empty properties values

### ISSUE THREAD

**Issue by roldevg** [klyashko/jms-messenger#4]
I tried to connect and browse ActiveMQ queues, but I got an error.
I have seen the code and my opinion the problem in empty values for some properties.
If I get free time in the nearest future I could fix :)

```
An exception han been thrown during loading messages from a queue
Details: INTE.IN

java.lang.NullPointerException
	at com.idea.tools.jms.AbstractConnectionStrategy.mapProperties(AbstractConnectionStrategy.java:99)
	at com.idea.tools.jms.AbstractConnectionStrategy.mapMessage(AbstractConnectionStrategy.java:65)
	at com.idea.tools.jms.AbstractConnectionStrategy.mapTextMessage(AbstractConnectionStrategy.java:73)
	at com.idea.tools.jms.AbstractConnectionStrategy.map(AbstractConnectionStrategy.java:21)
	at com.idea.tools.service.JmsService.receive(JmsService.java:89)
	at com.idea.tools.task.LoadMessagesTask.run(LoadMessagesTask.java:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by klyashko** [comment]
Thank you for the information.
I'll also try to take a look at that in nearest time :)

**Comment by klyashko** [comment]
The new version (1.1.0) of plugin is available in the repository.  Can you check that it fixes your problem?

**Comment by roldevg** [comment]
> The new version (1.1.0) of plugin is available in the repository. Can you check that it fixes your problem?

Yeah, I could check next week :)

**Comment by roldevg** [comment]
Fixed, thanks.
