### ISSUE TITLE
Jms Messenger no content and no button

### ISSUE THREAD

**Issue by YangShizhao** [klyashko/jms-messenger#9]
Hi, I am using Jms Messenger to send message to kafka, the first time I installed this tool, all works well, I added the server and saved two templates. But today, when I opened IDEA and started to work, I find that Jms is empty, I couldn't find any button or the templates I saved before, like this:
![image](https://user-images.githubusercontent.com/13344900/86553405-3e952380-bf7d-11ea-84d3-4aeb4da66154.png)

Then I go to IDEA setting page, the tool is still there and all looks good:
![image](https://user-images.githubusercontent.com/13344900/86553465-62f10000-bf7d-11ea-9db7-7442a238d488.png)

After I click the "save" button, the server info cameback, but I still can't send any message because either double click the template or right-click it, the "send message" dialog is not shown.
![image](https://user-images.githubusercontent.com/13344900/86553616-d5fa7680-bf7d-11ea-8e87-1ef4ca4629bf.png)

Is there some settings I messed up or is this an issue?

**Comment by klyashko** [comment]
Hi @YangShizhao 
I'll check what can be the reason for your problem in some nearest time.
What version of Idea do you use? Did you update it before it happened?

**Comment by YangShizhao** [comment]
> Hi @YangShizhao
> I'll check what can be the reason for your problem in some nearest time.
> What version of Idea do you use? Did you update it before it happened?

Here's my work environment detials, I don't remember there's a recent update.
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 972M
Cores: 8
Non-Bundled Plugins: Lombook Plugin, org.sonarlint.idea, mobi.hsz.idea.gitignore, io.protostuff.protostuff-jetbrains-plugin, jms-messenger, JProfiler

**Comment by klyashko** [comment]
Thanks a lot for the information.
Few more questions. Did you update idea before it happened or was it the same version? And how often it happens for you?

**Comment by YangShizhao** [comment]
> Thanks a lot for the information.
> Few more questions. Did you update idea before it happened or was it the same version? And how often it happens for you?

It happened two times, the most recently time is now, when checking the IDEA, I found an exception message, looks like below:
![image](https://user-images.githubusercontent.com/13344900/86909665-03484f80-c14b-11ea-8dd5-f5667ccfc5f1.png)

I copyed the full error message: 
Access is allowed from event dispatch thread with IW lock only.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@4232775d
Current thread: Thread[ApplicationImpl pooled thread 1,4,Idea Thread Group] 425137638
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1560205452
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1057)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1039)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1071)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:202)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at com.intellij.openapi.ui.SimpleToolWindowPanel.setToolbar(SimpleToolWindowPanel.java:97)
	at com.idea.tools.utils.GuiUtils.installActionGroupInToolBar(GuiUtils.java:54)
	at com.idea.tools.view.ServersBrowseToolPanel.installActionsInToolbar(ServersBrowseToolPanel.java:121)
	at com.idea.tools.view.ServersBrowseToolPanel.init(ServersBrowseToolPanel.java:103)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:458)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivities(StartupManagerImpl.java:410)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:258)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$0(StartupManagerImpl.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:257)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:145)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Hope it can help, thanks for your time.

**Comment by klyashko** [comment]
Thanks.
I'll check the problem in the nearest time.

**Comment by klyashko** [comment]
Hi @YangShizhao.
Plugin with fix is available in the repository.
